Repository quocnguyencoder/EMenu, pull requests merged in 2022-06, with the labels that each got.

#32 [BUG] Application error: a client-side exception has occurred
  components/AdminPage/Dashboards/ChartIncome.tsx
  components/AdminPage/Dashboards/ChartOrders.tsx
  components/AdminPage/Dashboards/ChartTotalOrders.tsx
  components/AdminPage/Dashboards/ChartTotalStars.tsx
Labels: bug

#38 clean up code
  components/Explore/PlaceCard.tsx
  components/Header/CartInfo.tsx
  components/Header/CartWithDrawer.tsx
  components/Header/IconWithDrawer.tsx
  components/Header/Logo.tsx
  components/Homepage/Banners.tsx
  components/Homepage/Discovery.tsx
  components/Homepage/FeaturedPlace.tsx
  components/Homepage/HeroText.tsx
  components/Homepage/PlaceRatings.tsx
  components/Homepage/index.tsx
  components/common/CircleCheck.tsx
  next.config.js
  pages/admin.tsx
  pages/checkout.tsx
  pages/e-menu/login.tsx
  pages/explore/[locationID].tsx
  pages/index.tsx
  pages/login.tsx
  pages/user/orders.tsx
  pages/user/profile.tsx
  pages/user/register-place.tsx
  pages/user/saved.tsx
  public/sw.js.map
  styles/Success.module.css
  styles/hero.ts
Labels: invalid

#47 add RatedOrder statistic function
  components/AdminPage/Nav.tsx
  components/AdminPage/OrderManagement/index.tsx
  components/AdminPage/RatedOrder/ModalRatedOrder.tsx
  components/AdminPage/RatedOrder/RatingStatistic.tsx
  components/AdminPage/RatedOrder/RatingTable.tsx
  components/AdminPage/RatedOrder/index.tsx
  pages/admin.tsx
  public/sw.js.map
Labels: enhancement

#48 46 final updates
  .babelrc
  components/Checkout/Crypto.tsx
  components/Detail/AddReview.tsx
  components/Detail/CategoryNav.tsx
  components/Detail/ItemList.tsx
  components/Detail/MenuItemCard.tsx
  components/Detail/PlaceInfo.tsx
  components/Detail/PlaceInfoModal.tsx
  components/Detail/PlaceMenu.tsx
  components/Detail/ReviewBlock.tsx
  components/Detail/TopReviews.tsx
  components/Explore/DistanceFilter.tsx
  components/Explore/FilterButtons.tsx
  components/Explore/PlaceCard.tsx
  components/Explore/PriceFilter.tsx
  components/Explore/RatingFilter.tsx
  components/Header/Logo.tsx
  components/Homepage/FeaturedPlace.tsx
  components/Homepage/HeroImage.tsx
  helpers/toAvgPrice.ts
  next-env.d.ts
  next.config.js
  package.json
  pages/explore/[locationID].tsx
  pages/login.tsx
  public/sw.js.map
  styles/cart.ts
  styles/explore.ts
  styles/hero.ts
  styles/theme.ts
  yarn.lock
Labels: enhancement
